### ISSUE TITLE
Error: Global connection already exists. Call sql.close() first.

### ISSUE THREAD

**Issue by scdebaay** [redconnect-io/node-red-contrib-mssql#15] opened 2017-04-11 13:34 UTC
When calling a MSSQL node anew the debug node comes back with:
Error: Global connection already exists. Call sql.close() first.
I suppose that the call should be issued in NodeJS or NodeRed, in the background. 
But this might give rise to the Error Connection is closed?

A way should be found to close connections gracefully, but not too soon.

**Comment by scdebaay** [comment] 2017-04-11 13:37
I think the issue is here:
    this.connection = sql;
			/*
			node.on('close',function(){
   			node.pool.close(function(){});
   		})
			*/
}

but not sure whether this was commented out on purpose...

**Comment by rafaelcst** [comment] 2017-04-12 20:05
In which file did you uncomment this code?

**Comment by guiandmag** [comment] 2017-04-12 20:10
I'm getting this same issue in my node-red, when I try to do a GET in a endpoint, then I try to do a GET in an other endpoint, this message is shown, then I need to restart my node-red to work it well. But if I try to do the GET in an other endpoint, the same issue persists.

**Comment by svm1** [comment] 2017-04-13 08:24
I'm getting the following error for  the below code, while connecting? Can any one find out the reason why it happening like that?

if (globalConnection) throw new Error('Global connection already exists. Call sql.close() first.')
                        ^

Error: Global connection already exists. Call sql.close() first.

exports.WriteToDB = function(sqlquery, callback){
    //var conn = new sql.Connection(dbConfig);
    sql.connect(dbConfig).then(function () {
        var req = new sql.Request(sql);
        req.query(sqlquery).then(function (recordset) {
            sql.close();
            callback(recordset);
        }).catch(function (err) {
            console.log(err);
            callback(null, err);
        });
    }).catch(function (err) {
        sql.close();
        console.log(err);
        callback(null, err);
    });
}

**Comment by scdebaay** [comment] 2017-04-13 08:41
@rafaelcst ,
I found it in MSSQL.js line 24 and onwards. The code is commented out in this version.
But it seems that the call is needed to clean up the connection. It is now open indefinitely, untill node-red restart?

**Comment by Isaksson** [comment] 2017-04-15 12:47
@scdebaay 
Same problem here, have you tried to change the code and see if it solves the issue?

**Comment by wrathagom** [comment] 2017-04-15 12:58
Hey folks, I think you're making this out to be more difficult than it is. This library doesn't use connection pools. That code is commented out because connection pools proved to cause other problems in the Node-Red Environment. Instead this library makes a connection at each and every request and the connection is closed when the request finishes.

As such one node cannot field more than one request at a time. If you do so you will get the `Error: Global connection already exists. Call sql.close() first.` error.

**Comment by Isaksson** [comment] 2017-04-15 14:42
There is no problem if you make a request and that is finished with success.
But if you make a request that for some reason fails then you can't make a new one, then you have to restart Node-RED before a new request could be made.

I have verified this error, just enter an address or port that not accept connection and when the Node reach the timeout then it will not accept any new requests.

**Comment by wrathagom** [comment] 2017-04-15 15:12
I was able to reproduce so I see what you mean.  I would imagine adding in some node.connection.close() statement's in the `catch` blocks would probably be what solves this, let me try it and see if it solves the problem.

**Comment by wrathagom** [comment] 2017-04-15 15:32
Or should we just pull this in and use pools? I wonder if it still suffers from it?

https://github.com/alessh/node-red-contrib-mssql

Caleb

**Comment by wrathagom** [comment] 2017-04-15 16:46
Never mind, this is all due to a breaking release in the underlying node-mssql package. It went from v3 to v4 with breaking changes. For the moment I am going to try and get a pull request accepted that locks the version below 4.0 while I/someone else work on compatibility with the new version.

**Comment by Isaksson** [comment] 2017-04-15 18:03
Have you noticed any more problems when using version 4? Or is it only the connection issue?

**Comment by wrathagom** [comment] 2017-04-15 18:04
The returned result format changed as well... but that is as far as I have looked.

**Comment by Isaksson** [comment] 2017-04-15 18:17
Ahh okey, I just installed it today for first time so I did not have anything to compare with so I did not notice the format changes.

**Comment by Isaksson** [comment] 2017-04-15 18:35
Iam going to continue to run against version 4 just to find out what needs to be changed.

This is what I do now just to make it runnable

Add stop function so that there will not be any errors when modifying the configuration or Node
`node.on('close',function(){
		node.connection.close()
        })`

And also added `node.connection.close()` in the catch blocks to make it possible to create a new connection if the last one failed.

I also noticed that a change of port from default 1433 to something  else does not break the connection so it seems the port is not mapped correct now, I will look into that also.

**Comment by fitz0019** [comment] 2017-04-15 18:53
FYI I've accepted @wrathagom's PR to fix the version below 4 because of the breaking changes. Does this make the issue closed? I'm open for a PR for 4 compatibility. Thanks again for your help :)

**Comment by Isaksson** [comment] 2017-04-15 19:46
It's ok for me to close it, I think we could say that the initial issue is solved with that PR.

**Comment by Isaksson** [comment] 2017-04-17 08:13
Will you push the change to npm also so that not all new installations will get the same error.

**Comment by fitz0019** [comment] 2017-04-17 08:16
@Isaksson Ah, I forgot to say on this issue (left a comment on the PR). I've already pushed the change to NPM as 0.0.7.

**Comment by Isaksson** [comment] 2017-04-17 08:19
Ahh perfect :)

**Comment by Isaksson** [comment] 2017-04-17 08:25
I found that there was two versions on NPM and both pointing to your github, one with version 0.1.0 node-red-contrib-mssql-port and the one that now is updated 0.0.7 node-red-contrib-mssql

Is there a reason for the two?

**Comment by wrathagom** [comment] 2017-04-17 14:29
The second looks like it was submitted by someone else right? Probably have to ask them why they submitted it from he same repo...

**Comment by Isaksson** [comment] 2017-04-17 14:36
Yes, I think so.
It could cause some confusion when it is like this, I know this has nothing to do with this issue but I did not find any other place to start this conversation, and I maybe the author does not know that someone else is pointing to the repo?

**Comment by fitz0019** [comment] 2017-04-18 07:34
@Isaksson I believe someone has forked this and added their own functionality but hasn't changed the package.json hence the link back here and the confusion. I'm not sure there is much I can do apart from ask them to change it. However if the functionality would benefit everyone perhaps the intention is to make a PR back here at some point. Thanks for pointing it out.

**Closed** 2017-04-18 07:35 UTC
